//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odalar
    {
        public int odaNumarası { get; set; }
        public string Odatipi { get; set; }
        public Nullable<int> OdaFiyatı { get; set; }
        public string OdaÖzellik { get; set; }
        public string OdaResım { get; set; }
    }
}
